# -*- mode: python ; coding: utf-8 -*-
"""
YouVideo Downloader — Ultimate Cross-Platform PyInstaller Spec v2.1
====================================================================
Professional builds for Linux · Windows · macOS with proper icons
Uses output from create_icon.py (ICO/ICNS/PNGs/Favicon)
Switched to --onedir mode for reliable Linux .deb packaging
(onedir is strongly recommended for system packages like .deb)
Features:
• Platform-specific icons (ICO/ICNS/PNG)
• Smart binary naming
• Optional FFmpeg bundling
• Comprehensive hidden imports
• UPX compression
• Version info (Windows)
• Code signing ready (macOS)
• Full data/assets bundling
"""

import sys
import os
from pathlib import Path

# ═══════════════════════════════════════════════════════════════════════════
# PLATFORM DETECTION
# ═══════════════════════════════════════════════════════════════════════════
IS_WINDOWS = sys.platform.startswith("win") or sys.platform == "cygwin"
IS_MACOS = sys.platform == "darwin"
IS_LINUX = sys.platform.startswith("linux")

print("=" * 80)
print(f"🔨 Building YouVideo Downloader - PyInstaller Spec v2.1")
print("=" * 80)
print(f"Platform: {sys.platform}")
print(f"Python: {sys.version.split()[0]}")
print(f"Mode: onedir (recommended for .deb/AppImage packaging)")

# ═══════════════════════════════════════════════════════════════════════════
# ICON CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════
def find_icon():
    """Find the best icon file generated by create_icon.py"""
    icon_dir = Path("assets/icons")
    
    if not icon_dir.exists():
        print(f"⚠️ Icon directory not found: {icon_dir}")
        return None
    
    if IS_WINDOWS:
        candidates = ["appicon.ico"]
    elif IS_MACOS:
        candidates = ["appicon.icns"]
    else:  # Linux
        candidates = ["icon_512.png", "icon_256.png", "appicon.png"]
    
    for candidate in candidates:
        icon_file = icon_dir / candidate
        if icon_file.exists():
            print(f"✅ Selected icon: {icon_file}")
            return str(icon_file)
    
    print(f"⚠️ No suitable icon found in {icon_dir}")
    return None

icon_file = find_icon()

# ═══════════════════════════════════════════════════════════════════════════
# BINARY NAMING
# ═══════════════════════════════════════════════════════════════════════════
if IS_LINUX:
    binary_name = "youvideo-downloader"
else:
    binary_name = "YouVideo Downloader"

print(f"📦 Binary name: {binary_name}")

# ═══════════════════════════════════════════════════════════════════════════
# FFMPEG BUNDLING (OPTIONAL)
# ═══════════════════════════════════════════════════════════════════════════
import shutil

def find_ffmpeg():
    ffmpeg_path = shutil.which("ffmpeg")
    if ffmpeg_path:
        print(f"✅ FFmpeg found: {ffmpeg_path} (will be bundled)")
        return [(ffmpeg_path, ".")]
    else:
        print(f"⚠️ FFmpeg not found – app will download on first use")
        return []

ffmpeg_binaries = find_ffmpeg()

# ═══════════════════════════════════════════════════════════════════════════
# HIDDEN IMPORTS
# ═══════════════════════════════════════════════════════════════════════════
hidden_imports = [
    "PySide6.QtCore",
    "PySide6.QtGui",
    "PySide6.QtWidgets",
    "PySide6.QtNetwork",
    "yt_dlp",
    "yt_dlp.extractor",
    "yt_dlp.postprocessor",
    "yt_dlp.utils",
    "urllib3",
    "certifi",
    "charset_normalizer",
    "ssl",
    "_ssl",
    "json",
    "xml.etree.ElementTree",
    "platform",
    "subprocess",
    "tempfile",
    "shutil",
    "PIL",
    "PIL.Image",
    "PIL.ImageQt",
]

print(f"📚 Hidden imports: {len(hidden_imports)} modules")

# ═══════════════════════════════════════════════════════════════════════════
# DATA FILES (assets + source modules)
# ═══════════════════════════════════════════════════════════════════════════
datas = [
    ("assets/qss", "assets/qss"),
    ("assets/icons", "assets/icons"),
    ("assets/screenshot", "assets/screenshot"),
]

# Add project Python packages/modules
for module_dir in ["downloader", "ui", "utils"]:
    if Path(module_dir).is_dir():
        datas.append((module_dir, module_dir))

print(f"📁 Data directories bundled: {len(datas)}")

# ═══════════════════════════════════════════════════════════════════════════
# ANALYSIS
# ═══════════════════════════════════════════════════════════════════════════
a = Analysis(
    ["main.py"],
    pathex=[],
    binaries=ffmpeg_binaries,
    datas=datas,
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "matplotlib",
        "numpy",
        "pandas",
        "scipy",
        "IPython",
        "notebook",
        "PyQt5",
        "PyQt6",
        "wx",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

# ═══════════════════════════════════════════════════════════════════════════
# PYZ
# ═══════════════════════════════════════════════════════════════════════════
pyz = PYZ(a.pure, a.zipped_data, cipher=None)

# ═══════════════════════════════════════════════════════════════════════════
# EXE (ONEDIR MODE)
# ═══════════════════════════════════════════════════════════════════════════
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    name=binary_name,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    console=False,  # GUI app
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=icon_file,
)

# ═══════════════════════════════════════════════════════════════════════════
# COLLECT (REQUIRED FOR ONEDIR MODE)
# ═══════════════════════════════════════════════════════════════════════════
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name=binary_name,  # Output directory name
)

# ═══════════════════════════════════════════════════════════════════════════
# macOS APP BUNDLE (OPTIONAL)
# ═══════════════════════════════════════════════════════════════════════════
if IS_MACOS:
    app = BUNDLE(
        coll,
        name="YouVideo Downloader.app",
        icon=icon_file,
        bundle_identifier="com.sarwarhossain.youvideo-downloader",
        version="2.0.0",  # Update as needed
        info_plist={
            'CFBundleName': 'YouVideo Downloader',
            'CFBundleDisplayName': 'YouVideo Downloader',
            'CFBundleIdentifier': 'com.sarwarhossain.youvideo-downloader',
            'CFBundleVersion': '2.0.0',
            'CFBundleShortVersionString': '2.0.0',
            'NSHighResolutionCapable': True,
            'LSMinimumSystemVersion': '10.15.0',
            'NSRequiresAquaSystemAppearance': False,
        },
    )
    print("✅ macOS .app bundle configured")

# ═══════════════════════════════════════════════════════════════════════════
# BUILD SUMMARY
# ═══════════════════════════════════════════════════════════════════════════
print("=" * 80)
print("✅ Spec configuration complete!")
print("=" * 80)
print(f"📦 Output directory: dist/{binary_name}")
if IS_MACOS:
    print(f"📦 macOS bundle: dist/YouVideo Downloader.app")
print(f"🎨 Icon: {icon_file or 'None'}")
print(f"🔧 FFmpeg bundled: {'Yes' if ffmpeg_binaries else 'No'}")
print(f"🛠  Build mode: onedir (perfect for .deb and AppImage)")
print("=" * 80)
print("\n🚀 Run: pyinstaller youvideo-downloader.spec")
print("\n💡 Why onedir?")
print("   • Reliable for Linux system packaging (.deb)")
print("   • No temporary extraction at runtime")
print("   • Better integration with desktop environments")
print("   • Easier debugging and patching")
print("\n   For portable single-file builds, use --onefile manually.")
print("=" * 80)